quarkus.json-rpc.js-client.enabled=true
quarkus.smallrye-graphql.js-client.enabled=true
quarkus.smallrye-openapi.js-client.enabled=true

# OIDC - Dev Services with custom realm (public client + test users)
quarkus.oidc.application-type=service
quarkus.keycloak.devservices.realm-path=quarkus-realm.json
