quarkus.json-rpc.js-client.enabled=true
quarkus.smallrye-graphql.js-client.enabled=true
quarkus.smallrye-openapi.js-client.enabled=true

# OIDC - Dev Services will auto-start Keycloak
quarkus.oidc.application-type=service
quarkus.oidc.devservices.roles.alice=user,admin
quarkus.oidc.devservices.roles.bob=user
